### ISSUE TITLE
Punctuation?

### ISSUE THREAD

**Issue by emilmuller** [neuspell/neuspell#6]
Hi!

Great library!

Would it be possible to let it correct punctuation as well? E.g. missing commas, too many commas, etc.

**Comment by murali1996** [comment]
Hi @emilmuller , As of now, the library only supports sequence modeling, meaning a one-to-one mapping between inputs and outputs. So for every input token, there will be exactly one token as a prediction. Because of this setup, missing commas (or any missing punctuations) cannot be handled as-is. 

We are more than happy to see interested practitioners taking this up and working on extending such additional functionalities. One way to add such functionality is by modifying the setup to a sequence generation task.
